export * from "page/CustomerManagementPage";
export * from "page/OrderListPage";
export * from "page/OrderRegistryPage";
export * from "page/PhoneCallRecordPage";
export * from "page/preferences/PreferencesPage";
export * from "page/preferences/PreferencesCidPage";
export * from "page/preferences/PreferencesPrinterPage";
export * from "page/ProductManagementPage";
export * from "page/StatisticsPage";
